### ISSUE TITLE
[BUG] `Segmentation fault at 0x0000000000000000` in `rb_fiber_transfer`

### ISSUE THREAD

**Issue by casperisfine** [socketry/io-event#113]
Opening here first because I'm too unfamiliar with this to know whether it's a Ruby bug or a bug in `io-event`. All I can say is that `rb_fiber_transfer` expects `rb_current_execution_context()` to return something, but it's called from a thread that doesn't have a current execution context. 

So I don't know if it's IO-event trying to resume a fiber from a wrong thread or wrong assumption in `rb_fiber_transfer`.

I unfortunately don't have a repro script, but this is happening on a fairly frequent basis (dozens of times a day).

```
/artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/scheduler.rb:167: [BUG] Segmentation fault at 0x0000000000000000
ruby 3.4.0dev (2024-08-27T14:45:53Z v3.4.0-pshopify-pr.. 2863085136) +YJIT [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0016 p:---- s:0100 e:000099 CFUNC  :resume
c:0015 p:0011 s:0095 e:000094 METHOD /artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/scheduler.rb:167
c:0014 p:0026 s:0089 E:001cf8 METHOD /artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/task.rb:421
c:0013 p:0018 s:0084 E:001c98 METHOD /artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/task.rb:189
c:0012 p:0033 s:0079 e:000078 METHOD /artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/task.rb:215 [FINISH]
c:0011 p:0024 s:0071 e:000070 METHOD /artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/kernel/async.rb:26
c:0010 p:0004 s:0061 E:0004c8 METHOD /artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/async_client.rb:370
c:0009 p:0008 s:0054 E:001c08 BLOCK  /artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/async_client.rb:156
c:0008 p:0012 s:0050 e:000049 METHOD /artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/instrumentation/timings.rb:67
c:0007 p:0021 s:0042 E:002398 METHOD /artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/async_client.rb:155
c:0006 p:0027 s:0031 e:000027 BLOCK  /artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/async_client.rb:129
c:0005 p:0012 s:0025 e:000024 METHOD /artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/instrumentation/timings.rb:67
c:0004 p:0015 s:0017 e:000016 BLOCK  /artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/async_client.rb:128
c:0003 p:0011 s:0013 e:000012 BLOCK  /artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/task.rb:190
c:0002 p:0004 s:0009 e:000007 BLOCK  /artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/task.rb:403 [FINISH]
c:0001 p:---- s:0003 e:000002 DUMMY  [FINISH]

-- Ruby level backtrace information ----------------------------------------
/artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/task.rb:403:in 'block in schedule'
/artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/task.rb:190:in 'block in run'
/artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/async_client.rb:128:in 'block (2 levels) in _process'
/artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/instrumentation/timings.rb:67:in 'measure'
/artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/async_client.rb:129:in 'block (3 levels) in _process'
/artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/async_client.rb:155:in 'make_request'
/artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/instrumentation/timings.rb:67:in 'measure'
/artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/async_client.rb:156:in 'block in make_request'
/artifacts/bundle/ruby/3.4.0+0/gems/runtime-engine-client-0.10.1/lib/runtime_engine/async_client.rb:370:in 'timeout'
/artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/kernel/async.rb:26:in 'Async'
/artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/task.rb:215:in 'async'
/artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/task.rb:189:in 'run'
/artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/task.rb:421:in 'schedule'
/artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/scheduler.rb:167:in 'resume'
/artifacts/bundle/ruby/3.4.0+0/gems/async-2.14.2/lib/async/scheduler.rb:167:in 'resume'

-- Threading information ---------------------------------------------------
Total ractor count: 1
Ruby thread count for this ractor: 16

-- Machine register context ------------------------------------------------
 RIP: 0x00005b77a8f4971f RBP: 0x00007fd19fa2c500 RSP: 0x00007fd23a74b970
 RAX: 0x00007fd25504d000 RBX: 0x00007fd1feb42800 RCX: 0x0000000000000000
 RDX: 0x00007fd255068280 RDI: 0x00007fd1febd44a0 RSI: 0x00007fd19fa3a7a0
  R8: 0x0000000000000001  R9: 0x00007fd207a14c40 R10: 0x00007fd16c93d0b0
 R11: 0x0000000000000002 R12: 0x00007fd19fa3a580 R13: 0x00007fd23a74b920
 R14: 0x00007fd23a74b920 R15: 0x00005b77a91b12a0 EFL: 0x0000000000010287

-- C level backtrace information -------------------------------------------
/usr/local/ruby/bin/ruby(rb_print_backtrace+0x14) [0x5b77a8dbe0c1] /tmp/ruby-build/ruby-3.4.0-pshopify-preview5/vm_dump.c:820
/usr/local/ruby/bin/ruby(rb_vm_bugreport) /tmp/ruby-build/ruby-3.4.0-pshopify-preview5/vm_dump.c:1151
/usr/local/ruby/bin/ruby(rb_bug_for_fatal_signal+0xfc) [0x5b77a8f768dc] /tmp/ruby-build/ruby-3.4.0-pshopify-preview5/error.c:1087
/usr/local/ruby/bin/ruby(sigsegv+0x46) [0x5b77a8d05be6] /tmp/ruby-build/ruby-3.4.0-pshopify-preview5/signal.c:929
/lib/x86_64-linux-gnu/libc.so.6(0x7fd255732520) [0x7fd255732520]
/usr/local/ruby/bin/ruby(rb_current_execution_context+0x0) [0x5b77a8f4971f] /tmp/ruby-build/ruby-3.4.0-pshopify-preview5/cont.c:2677
/usr/local/ruby/bin/ruby(fiber_current) /tmp/ruby-build/ruby-3.4.0-pshopify-preview5/cont.c:2067
/usr/local/ruby/bin/ruby(fiber_switch) /tmp/ruby-build/ruby-3.4.0-pshopify-preview5/cont.c:2771
/usr/local/ruby/bin/ruby(rb_fiber_transfer) /tmp/ruby-build/ruby-3.4.0-pshopify-preview5/cont.c:2795
/usr/local/ruby/bin/ruby(rb_ensure+0x10c) [0x5b77a8baa5ac] /tmp/ruby-build/ruby-3.4.0-pshopify-preview5/eval.c:1000
/artifacts/bundle/ruby/3.4.0+0/gems/io-event-1.6.5/lib/IO_Event.so(IO_Event_Selector_resume+0x9c) [0x7fd21526bf2c] ./io/event/selector/selector.c:234
/artifacts/bundle/ruby/3.4.0+0/gems/io-event-1.6.5/lib/IO_Event.so(IO_Event_Selector_resume) (null):0
[0x5b77aaae022f]
```

**Comment by ioquatix** [comment]
Thanks for your report, I will take a look tomorrow.

If I prepare a debug release, would you be able to test it?

**Comment by casperisfine** [comment]
Of `io-event` possibly yes. Of Ruby, no I'm afraid I can't.

**Comment by ioquatix** [comment]
I have a couple of questions to help me understand the nature of the problem.

1. Is this issue occurring inside Falcon or are you using `Async{...}` inside an existing server?
2. Can you please elaborate on the setup and/or organization of threads and if you know, the specific work/operation that is causing this error e.g. `async-http` client request, `async-redis`, some other native library.
3. Are you using connection pooling for the above, and if so, what library is doing that? e.g. `async-pool`, `connection-pool`, ActiveRecord's own connection pooling, etc.

**Comment by casperisfine** [comment]
> I have a couple of questions to help me understand the nature of the problem.

Ok, but keep in mind I'm here with some sort of SRE hat. I don't know the code using `async` at all, I'm just seeing segfaults. And since it's `async` I don't even have a backtrace to see if there is a pattern in the code that trigger this.

> Is this issue occurring inside Falcon or are you using Async{...} inside an existing (alternative) server? Can you provide any details?

Yeah, it's running inside Pitchfork, in a fairly gigantic application.

> Can you please elaborate on the setup and/or organization of threads and if you know, the specific work/operation that is causing this error

Yeah, unfortunately I don't know that, and as mentioned I can't just rely on the backtrace to point me at the calling code like I usually do for this sort of issues. All I know is that it's in a generic `/graphql` endpoint, so it could be anything... All I can say is the gems used:

```
$ rg -F 'async-' Gemfile.lock 
1905:      async-io (>= 1.41.0)
2368:      async-http (>= 0.67, < 0.70)
2604:    async-http (0.69.0)
2606:      async-pool (~> 0.7)
2613:    async-io (1.43.2)
2615:    async-pool (0.8.0)
```

So I think it's a pool of HTTP connections? If I grep for `Async do` I find a couple callsites:

```ruby
        results = Async do |task|
          tasks = batch_entries.map do |batch_entry|
            task.async do
              run_with_cache(batch_entry.context, batch_entry.http_request)
            end
          end

          tasks.map(&:wait)
        end.wait
```

```ruby
            Async do |task_scheduler|
              tasks = scope_key_to_missing_fetch_results.map do |scope_key, missing_fetch_results|
                task_scheduler.async do
                  perform_fetch(scope_key: scope_key, fetch_results: missing_fetch_results)
                rescue StandardError => e
                  missing_fetch_results.each do |fetch_result|
                    fetch_result.error_result = e.message
                  end
                  log_fetch_error(e, message: "[REDACTED]")
                end
              end
              tasks.map(&:wait)
            end.wait
```

That seems to be all what it's used for.

As for the organization of threads, as you can see in the crash report there's 16 Ruby threads, but also a whole lot of native threads started by gems like `grpc`.  But these are mostly all "service threads" AFAICT `Async` is only called from the main thread.

> Are you able to clarify "happening on a fairly frequent basis (dozens of times a day)." - as in a percentage of total requests/operations 

Well, I don't know how often this codepath is called, but probably quite a lot, dozens of times a day isn't a whole lot for us, probably `0.000001%` or something like that, but this was to say it's not a once in a blue-moon issue.

**Comment by ioquatix** [comment]
Thanks, that's helpful.

**Comment by trevorturk** [comment]
The mention of `/graphql` makes me want to call attention to the new `AsyncDataloader` stuff in `graphql-ruby`, just in case that might be relevant. I'm not sure if @rmosolgo might be worth looping in, in case he has any ideas. I doubt Shopify is using `AsyncDataloader` yet, but you never know! (Apologies if this is unhelpful / a red herring...)

**Comment by casperisfine** [comment]
It's not specific to graphql, it's also failing on some non graphql endpoints.

**Comment by ioquatix** [comment]
I think I may have been missing some write barriers and GC marking.

https://github.com/socketry/io-event/commit/bef8e91a7370797b4c80bbad60a6c7f7214d0e79#diff-31f22093e996cbeba1998b1ac937570688b64c37f01a6f41a98586c83943683fR140-R145

I'm not sure if there is an easy way to confirm the fix, but I'll cut a release if everything looks good, and then maybe you can test it?

**Comment by casperisfine** [comment]
Thanks. I'll upgrade to `1.6.6` and report back next week.

**Comment by casperisfine** [comment]
Sorry, just realized the patch ain't in `1.6.6`, I'll try the main branch.

**Comment by ioquatix** [comment]
Sorry I fell asleep before I could make a release. Thanks for your efforts.

I'm going to try to write an artificial test scenario that causes the write barriers/GC marking to fail. I'd like to try and actually make a repro.

**Comment by casperisfine** [comment]
Hum, I deploy this a few hours ago, and I think the original error might be solved (still want to let it run longer).

However I've just noticed what seem to be a new type of crash, and seem to be even more frequent:

```
(ruby) : SIGABRT Unhandled signal SIGABRT in `/usr/local/ruby/bin/ruby` 
    [/usr/lib/x86_64-linux-gnu/libc.so.6] pthread_kill
    [/usr/lib/x86_64-linux-gnu/libc.so.6] raise
    [/usr/lib/x86_64-linux-gnu/libc.so.6] abort
    [/usr/local/ruby/bin/ruby] make_errno_exc_str
    /tmp/ruby-build/ruby-3.4.0-7387a0979158c50ca37884f14bad2b493d3e2f0a/gc.c:2059 gc_mark_internal
    io/event/selector/epoll.c:107 IO_Event_Selector_EPoll_Type_mark
    [/usr/local/ruby/bin/ruby] gc_start
    gc/default.c:6573 garbage_collect
    [/usr/local/ruby/bin/ruby] rb_gc_impl_malloc
    [/usr/local/ruby/bin/ruby] thread_create_core
    /tmp/ruby-build/ruby-3.4.0-7387a0979158c50ca37884f14bad2b493d3e2f0a/thread.c:948 thread_initialize
    [/usr/local/ruby/bin/ruby] vm_call0_body
    /tmp/ruby-build/ruby-3.4.0-7387a0979158c50ca37884f14bad2b493d3e2f0a/vm_eval.c:80 vm_call0_cc
    [/usr/local/ruby/bin/ruby] rb_call0
    /tmp/ruby-build/ruby-3.4.0-7387a0979158c50ca37884f14bad2b493d3e2f0a/vm_eval.c:1067 rb_funcallv_kw
    [/usr/local/ruby/bin/ruby] thread_s_new
    [/usr/local/ruby/bin/ruby] vm_call_cfunc_with_frame_
    /tmp/ruby-build/ruby-3.4.0-7387a0979158c50ca37884f14bad2b493d3e2f0a/vm_insnhelper.c:5932 vm_sendish
    [/usr/local/ruby/bin/ruby] vm_exec_core
```

**Comment by ioquatix** [comment]
It's also possible the new error is hiding/preventing the old error... I've made a new release, hopefully that fixes the above issue.

**Comment by ioquatix** [comment]
I've just released v1.7.0 which is fixing support for Windows, but also includes various fixes related to this discussion too.

**Comment by casperisfine** [comment]
> I think the original error might be solved (still want to let it run longer).

So it wasn't actually solved, it happened a few more times this morning.

**Comment by casperisfine** [comment]
I updated io-event in our app, and I'm afraid it's still crashing. I'll try to see if I can figure something out with the core dump.

**Comment by casperisfine** [comment]
So the crash is a "try to mark T_NONE", and it seem the T_NONE is `descriptor->io`

```
#12 0x00007a4e5919a5b5 in IO_Event_Selector_EPoll_Descriptor_mark (_descriptor=0x7a4d86213390) at ./io/event/selector/epoll.c:99
99	./io/event/selector/epoll.c: No such file or directory.
(gdb) p descriptor
$1 = (struct IO_Event_Selector_EPoll_Descriptor *) 0x7a4d86213390
(gdb) p *descriptor
$2 = {list = {head = 0x7a4d86213390, tail = 0x7a4d86213390, type = 0x0}, io = 134472390245920, waiting_events = (IO_EVENT_READABLE | IO_EVENT_WRITABLE), 
  registered_events = (IO_EVENT_READABLE | IO_EVENT_WRITABLE)}
(gdb) p *(struct RBasic *)134472390245920
$3 = {flags = 0, klass = 134472390279120}
```

**Comment by ioquatix** [comment]
@casperisfine thanks for all your contributions. I've merged them and released v1.7.1.

**Comment by casperisfine** [comment]
Alright, it seems this issue didn't happen over the week end, so I think it's fixed for good.

**Comment by ioquatix** [comment]
Thanks so much for your help fixing this bug and all the other contributions!
